version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: frontend
    network_mode: "host"
    depends_on:
      - celery_app

  celery_app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: celery_app
    network_mode: "host"
    depends_on:
      - redis
      - rabbitmq

  flower_app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: flower_app
    network_mode: "host"
    depends_on:
      - celery_app
      - redis
      - rabbitmq

  minio:
    image: minio/minio:RELEASE.2020-03-09T18-26-53Z
    command: server /data/minio/
    network_mode: "host"
    environment:
      MINIO_ACCESS_KEY: 'minio'
      MINIO_SECRET_KEY: 'minio123'

  redis:
    image: "redis:5.0-rc-alpine"
    command: redis-server --bind 0.0.0.0
    network_mode: "host"

  rabbitmq:
    image: "rabbitmq:3.10-management"
    network_mode: "host"
